### ISSUE TITLE
2.2.0 version does not work correct with cocoa pods

### ISSUE THREAD

**Issue by DmitryPR** [paymill/paymill-ios#9]
Hello,

I tried to use regular method of adding the library to the project but got this:
 [!] Unable to satisfy the following requirements:
- `PayMillSDK (~> 2.2.0)` required by `Podfile`

If I try to use the suggested way:
pod 'PayMillSDK', :git=>'https://github.com/paymill/paymill-ios.git', :branch=>'master', :tag=>'2.2.0'

The library does not get installed correctly. What is being installed in version 2.1.1 and the folder contains 2 files, Licence.md and README.md

I see this in install logs:
Cocoapods version 0.34.4
Installing PayMillSDK 2.1.1 (was 2.0.3)

**Comment by yalnazov** [comment]
Hi @DmitryPR , 

thanks for noting this. I will update the CocoaPods trunk by the end of the week.

**Comment by chrisdoc** [comment]
It is still not in the cocoapods central repository.

Cocoapods now require to publish new versions with ```pod trunk push``` however this fails cuz the current PayMillSDK podspec does not pass the lint test.
 
I opened a pull request to solve this issue

**Comment by appcelerate** [comment]
Hi @yalnazov ,

the issue is still open. I can't update my pods.

### Error

```
Errno::ENOENT - No such file or directory - /Users/user//iOS-App/Pods/PayMillSDK/samples/vouchermill/PayMillSDK/PayMillSDK.framework/Resources
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:905:in `stat'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:905:in `symbolic_modes_to_i'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:926:in `fu_mode'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1000:in `block (2 levels) in chmod_R'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1460:in `preorder_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:998:in `block in chmod_R'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:997:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:997:in `chmod_R'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:117:in `block in prepare'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:116:in `prepare'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:103:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:156:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

any advice?

**Comment by nikoloff** [comment]
Hi @appcelerate 

Thx for the report, we will take a look as soon as possible.

**Comment by chrisdoc** [comment]
@nikoloff 
any updates on this issue? it is really annoying to always execute
```bash
rm -rf Pods
pod install
```

**Comment by yalnazov** [comment]
@chrisdoc, @appcelerate, @DmitryPR  
sorry for the inconvenience. We will fix it in the course of the week.

**Comment by chrisdoc** [comment]
@yalnazov any updates, the only change last week was updating the readme.

As a company that uses PayMill for its transactions it is quite frustrating to wait for simple fixes for almost 2 months.

I really hope we will see a fix soon

**Comment by yalnazov** [comment]
@chrisdoc should be available in cocoapods central now. thanks for the pr and once more sorry for the inconvenience.

**Comment by appcelerate** [comment]
@chrisdoc the issue is already there...

**Comment by yalnazov** [comment]
@appcelerate sorry, but didn't quite get that. Are you still having issues with this? Thanks.
